name:                assignment2
version:             0.1.0.0
github:              "githubuser/assignment2"
license:             BSD3
author:              "Andrew Brennan"
maintainer:          "andrew-brennan@live.com"
copyright:           "andrew brennan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/assignment2#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
  - Charts
  - HtmlReport
  - Params
  - CovidData
  - StatReport
  - Lib

  dependencies:
    - bytestring >=0.10 && <0.12
    - blaze-html >=0.9 && <0.10
    - optparse-applicative >=0.14 && <0.17
    - time >=1.8 && <1.12
    - text >=1.2 && <1.3
    - fmt >=0.5 && <0.7
    - Chart >=1.8 && <1.10
    - Chart-diagrams >=1.8 && <1.10
    - cassava >=0.5 && <0.6
    - colonnade >= 1.1 && < 1.3
    - blaze-colonnade >= 1.1 && < 1.3
  

executables:
  assignment2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assignment2

tests:
  assignment2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assignment2
    - bytestring >=0.10 && <0.12
    - text >=1.2 && <1.3
    - cassava >=0.5 && <0.6
